# Generated by Django 4.2.4 on 2023-08-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_title', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AR', 'Arkansas')], max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], verbose_name='year')),
                ('condition', models.CharField(max_length=255)),
                ('price', models.IntegerField(max_length=100)),
                ('description', models.TextField()),
                ('car_photo', models.ImageField(upload_to='photo/%Y/%m/%d/')),
                ('car_photo_1', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('car_photo_2', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('car_photo_3', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('car_photo_4', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('features', models.CharField(choices=[('AC', 'Air Conditioner'), ('PW', 'Power Window'), ('SR', 'Sunroof')], max_length=255)),
                ('body_style', models.CharField(max_length=255)),
                ('engine', models.CharField(max_length=255)),
                ('transmission', models.CharField(max_length=255)),
                ('interior', models.CharField(max_length=255)),
                ('miles', models.IntegerField(max_length=100)),
                ('doors', models.IntegerField(choices=[('2', '2'), ('4', '4'), ('6', '6')], max_length=100)),
                ('passengers', models.IntegerField(max_length=100)),
                ('vin_no', models.CharField(max_length=255)),
                ('milage', models.IntegerField(max_length=100)),
                ('fuel_type', models.CharField(max_length=255)),
                ('no_of_owner', models.CharField(max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
