# Generated by Django 4.2.4 on 2023-08-14 04:16

import ckeditor.fields
from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_car_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='car',
            name='miles',
        ),
        migrations.RemoveField(
            model_name='car',
            name='vin_no',
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('2', '2'), ('4', '4'), ('6', '6')], max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AC', 'Air Conditioner'), ('PW', 'Power Window'), ('SR', 'Sunroof')], max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AR', 'Arkansas')], max_length=100),
        ),
    ]
